version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 999999999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - zookeeper

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  app1:
    build: .
    volumes:
      - ./server:/application
      - app-python-site-packages:/usr/local/lib/python3.6/site-packages
      - app-usr-local-bin:/usr/local/bin
      - worker-data1:/data/
    # command: "faust --datadir=/data/work_6067 -A app worker -l info --web-port 6067"
    command: tail -f /dev/null
    depends_on:
      - kafka

  app2:
    build: .
    volumes:
      - ./server:/application
      - app-python-site-packages:/usr/local/lib/python3.6/site-packages
      - app-usr-local-bin:/usr/local/bin
      - worker-data2:/data/
    # command: "faust --datadir=/data/work_6067 -A app worker -l info --web-port 6067"
    command: tail -f /dev/null
    depends_on:
      - kafka


volumes:
  redis_data:
    driver: local

  app-python-site-packages:
    driver: local

  app-usr-local-bin:
    driver: local

  worker-data1:
    driver: local

  worker-data2:
    driver: local
